# Generated by Django 3.1.7 on 2021-04-06 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountId', models.AutoField(primary_key=True, serialize=False)),
                ('accountNumber', models.CharField(max_length=200)),
                ('balance', models.IntegerField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('startingBalance', models.IntegerField(default=0)),
                ('endingBalance', models.IntegerField()),
                ('currentBalance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('pigId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminderId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('dob', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('test', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('loginId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='piggybankapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bankId', models.AutoField(primary_key=True, serialize=False)),
                ('bankName', models.CharField(max_length=100)),
                ('linkedDate', models.DateTimeField(auto_now=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=100)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='piggybankapp.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='piggybankapp.user'),
        ),
    ]
