# Generated by Django 3.2 on 2021-05-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggybankapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='type',
            new_name='reminderType',
        ),
    ]
